### ISSUE TITLE
Quick simultaneous clicks causing problems

### ISSUE THREAD

**Issue by CREEATION** [nashvail/Quttons#2]
When clicking a Qutton and then clicking outside of it while it's opening, weird things happen.

![quttons](https://cloud.githubusercontent.com/assets/3277769/8185344/e6863b78-1443-11e5-8706-0c531d0d3a6e.gif)

**Comment by nashvail** [comment]
Thanks for pointing out.

**Comment by nashvail** [comment]
@CREEATION would you mind doing a quick check if this still exists. Made some changes.
EDIT : Still needs a little more work

**Comment by CREEATION** [comment]
Yep :yum:

![bildschirmfoto 2015-06-16 um 18 10 18](https://cloud.githubusercontent.com/assets/3277769/8187926/082c744a-1453-11e5-9f22-65c226067f68.png)

**Comment by RicardoRFaria** [comment]
If RunSequence() had a pipeline of events or a promisse.

**Comment by nashvail** [comment]
@RoxRicardo RunSequence() can be broken down into promises. Adds a few more lines of code but it can be done.
