### ISSUE TITLE
Too many clicks

### ISSUE THREAD

**Issue by franciscoosnaya** [nashvail/Quttons#3]
When you click one Qutton, and next to that click another one, the Quantum Paper of the first displays, but unfocused, and the last Quantum Paper displays correctly. If, we click both of them, and next to it, click the last one, very quickly, the first two Quantum Papers are displayed but not correctly. Why is that? transition time? or animation time?

**Comment by nashvail** [comment]
@franciscoosnaya something like the gif shown here? https://github.com/nashvail/Quttons/issues/2

**Comment by franciscoosnaya** [comment]
yes, but playing with the demo, i managed to hide or delete the icons.. it's weird.. and even to move them..  it's ther ebut it's not there too.. 
![screen shot 2015-06-16 at 10 30 32 am](https://cloud.githubusercontent.com/assets/11889896/8186970/e1d1c632-1412-11e5-9d88-aba26a3ec863.png)
![screen shot 2015-06-16 at 10 30 31 am](https://cloud.githubusercontent.com/assets/11889896/8186975/e7603b9c-1412-11e5-8be8-4aa60d2ecf65.png)
![screen shot 2015-06-16 at 10 31 02 am](https://cloud.githubusercontent.com/assets/11889896/8186977/eb579a74-1412-11e5-94ee-83c0f8dc8509.png)

**Comment by nashvail** [comment]
@franciscoosnaya Yup, quick simultaneous clicks are causing problems. This seems to be a similar issue as #2 . So I am going to close this one. You can join me there at #2 .  Thanks.
