### ISSUE TITLE
Container flashing

### ISSUE THREAD

**Issue by CREEATION** [nashvail/Quttons#6]
Hello again,

when (double/tripple/...-) clicking on a Qutton, it's flashing.
See this gif:

![flash](https://cloud.githubusercontent.com/assets/3277769/8301456/468ebd3e-198e-11e5-9cc9-129d58c80887.gif)

**Comment by nashvail** [comment]
@CREEATION Thanks again! I guess this is just the not fully implemented fix on gh-pages branch causing issues. I have merged the fix with the gh-pages branch now. Would you mind checking one more time? Browsers cache scripts so it would be better tested in a different browser.

:P
![](http://media.giphy.com/media/119mPbgfgGnXig/giphy.gif)

**Comment by CREEATION** [comment]
Yep, works now :+1:
#gifsaved :D
