### ISSUE TITLE
Icon size

### ISSUE THREAD

**Issue by RicardoRFaria** [nashvail/Quttons#7]
What do you think about icon size parameter?

**Comment by nashvail** [comment]
Size is an intrinsic parameter of the supplied icon. Not necessary in my opinion. How do you think it can help?

**Comment by RicardoRFaria** [comment]
If my icon in bigger than the size of button, I can reduce the size using parameter.

**Comment by nashvail** [comment]
I think the user must be careful and smart enough to supply an icon smaller than the size of the button, handling that through code introduces unnecessary complexity.

**Comment by RicardoRFaria** [comment]
Make sense. Thanks.
